APP	= libuser

#############################################################################

include ../make/defaults.mk

all: install

clean:
	rm -f $(APP) $(DESTDIR)/$(APP)

$(APP): $(APP).c Makefile 
	$(CC) -o $@ $<  # add the lib search path and lib name

install: $(APP)
	cp $< $(DESTDIR)

